CREATE TABLE sys_account (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY
    ,username VARCHAR(255) NOT NULL
    ,account_status VARCHAR(2) NOT NULL
    ,create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,created_by BIGINT NOT NULL
    ,update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,updated_by BIGINT DEFAULT NULL
    ,version BIGINT NOT NULL DEFAULT 0
)
